baseURL = "https://www.deningunaparte.com/"
languageCode = "en-us"
title = "de ninguna parte"
theme = "deningunaparte"
preserveTaxonomyNames = true
enableEmoji = true

[params]
  description = "Photographs by Erik Zitzermann"
  author = "Erik Zitzermann"

[taxonomies]
  tag = "tags"
  # category = "categories"
  # series = "series"

[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"

[blackfriday]
  extensions = ["hardLineBreak"]
