baseURL = "/"
languageCode = "en-us"
title = "de ninguna parte"
theme = "deningunaparte"
preserveTaxonomyNames = true
enableEmoji = true

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[[menu.main]]
    name = "About"
    #pre = "<i class='fa fa-heart'></i>"
    #weight = -110
    identifier = "about"
    url = "/about/"
