baseURL = "/"
languageCode = "en-us"
title = "de ninguna parte"
theme = "deningunaparte"
preserveTaxonomyNames = true
enableEmoji = true
googleAnalytics = "UA-76665409-1"


[params]
  description = "Photographies by Erik Zitzermann"
  author = "Erik Zitzermann"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"

[blackfriday]
  extensions = ["hardLineBreak"]
